# Generated by Django 2.2.7 on 2021-06-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='訂單id')),
                ('product_id', models.IntegerField(verbose_name='商品id')),
                ('qty', models.IntegerField(verbose_name='購買數量')),
                ('price', models.IntegerField(verbose_name='商品單價')),
                ('shop_id', models.IntegerField(verbose_name='商品所屬館別')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='商品id')),
                ('stock_pcs', models.IntegerField(verbose_name='商品庫存數量')),
                ('price', models.IntegerField(verbose_name='商品單價')),
                ('shop_id', models.IntegerField(verbose_name='商品所屬館別')),
                ('vip', models.BooleanField(default=False, verbose_name='True => VIP限定/ False =>無限制購買對象')),
            ],
        ),
    ]
