# Generated by Django 2.2.7 on 2021-06-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shop_id',
            field=models.CharField(max_length=5, verbose_name='商品所屬館別'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop_id',
            field=models.CharField(max_length=5, verbose_name='商品所屬館別'),
        ),
    ]
