# Generated by Django 2.2.7 on 2021-06-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20210607_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.IntegerField(default=1, verbose_name='顧客id'),
            preserve_default=False,
        ),
    ]
