# Generated by Django 2.2.7 on 2021-06-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20210607_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
    ]
